CREATE TABLE PAYMENT (
    P_ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    P_SUM DECIMAL,
    P_DATE DATE,
    P_TO INT,
    P_FROM INT
 ); 

CREATE TABLE ENTITY (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    E_NAME VARCHAR(50)
 );



